name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm run build

    #发布到 guihua.github.io/main
    - name: Deploy guihua.github.io/main
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.WEBSITE_TOKEN }}
        EXTERNAL_REPOSITORY: guihua/guihua.github.io #可以新建一个 guihua.github.io 仓库发布到 main
        PUBLISH_BRANCH: main
        PUBLISH_DIR: docs/.vuepress/dist
      with:
        emptyCommits: false
